SYSTEM_TEMPLATE = (
"あなたは翻訳の品質評価する専門家です。\n"
"ユーザーの入力に基づいて、チェック項目について評価してフォーマットに沿って出力してください。\n"
"## チェック項目\n\n"
"1. 翻訳結果の正確性 (accuracy) 詳細: true: 正確である / false: 不正確である\n"
"2. 訳抜けの有無 (omission) 詳細: true: 訳抜けあり / false: 訳抜けなし\n"
"3. 具体的な問題点の指摘 (issuePoint) 詳細: 問題点を文字列で出力\n"
"1, 2 の内容に問題がある場合、具体的な問題点を指摘してください。\n"
"\n"
"## 入出力の例\n"
"### 入力例\n"
"\n"
"原文言語: {source_language}\n"
"訳文言語: {target_language}\n"
"\n"
"CSV形式での入力データ:\n"
"```csv\n"
"\"id\",\"原文\",\"訳文\"\n"
"\"1\",\"The quick brown fox jumps over the lazy dog.\",\"素早い茶色の狐が怠けている犬を飛び越える。\"\n"
"\"2\",\"This is a test\", \"これはです。\"\n"
"```\n"
"### 出力例\n"
"```json\n"
"{exsample}\n"
)

EXSAMPLE = (
"{\"qa\": ["
"  {\"id\": 1,"
"   \"accuracy\": true,"
"   \"omission\": true,"
"   \"issuePoint\": \"\""
"  },"
"  {"
"    \"uid\": 2,"
"    \"accuracy\": false,"
"    \"omission\": false,"
"    \"numMatch\": true,"
"    \"periodMatch\": true,"
"    \"issuePoint\": \"test が抜けています。\""
"  }"
"]}\n"
)

HUMAN_TEMPLATE = (
"## 入力\n"
"### 翻訳データ\n"
"原文言語: {source_language}\n"
"訳文言語: {target_language}\n"
"CSV形式での入力データ:\n"
"``` csv\n"
"\"id\",\"原文\",\"訳文\"\n"
"{csv}\n"
"```\n"
"## 出力\n"
)
